export const BOT_NAME_PREFIXES = [
  "Akkadian",
  "Babylonian",
  "Sumerian",
  "Hittite",
  "Phoenician",
  "Canaanite",
  "Minoan",
  "Mycenaean",
  "Etruscan",
  "Scythian",
  "Thracian",
  "Dacian",
  "Illyrian",
  "Median",
  "Chaldean",
  "Roman",
  "Greek",
  "Byzantine",
  "Persian",
  "Parthian",
  "Seleucid",
  "Ptolemaic",
  "Palmyrene",
  "Macedonian",
  "Carthaginian",
  "Ming",
  "Tang",
  "Song",
  "Yuan",
  "Mauryan",
  "Kushan",
  "Rajput",
  "Mughal",
  "Satavahana",
  "Vijayanagara",
  "Egyptian",
  "Nubian",
  "Kushite",
  "Aksumite",
  "Ethiopian",
  "Songhai",
  "Malian",
  "Ghanaian",
  "Benin",
  "Ashanti",
  "Zulu",
  "Tuareg",
  "Berber",
  "Kanem-Bornu",
  "Buganda",
  "Mossi",
  "Swahili",
  "Somali",
  "Wolof",
  "Umayyad",
  "Abbasid",
  "Ayyubid",
  "Fatimid",
  "Mamluk",
  "Seljuk",
  "Safavid",
  "Ottoman",
  "Almoravid",
  "Almohad",
  "Rashidun",
  "Ziyarid",
  "Frankish",
  "Visigothic",
  "Ostrogothic",
  "Viking",
  "Norman",
  "Saxon",
  "Anglo-Saxon",
  "Celtic",
  "Gaulish",
  "Carolingian",
  "Merovingian",
  "Capetian",
  "Plantagenet",
  "Tudor",
  "Stuart",
  "Habsburg",
  "Romanov",
  "Lancaster",
  "York",
  "Bourbon",
  "Napoleonic",
  "British",
  "French",
  "Spanish",
  "Portuguese",
  "Dutch",
  "Russian",
  "German",
  "Italian",
  "Swedish",
  "Norwegian",
  "Danish",
  "Polish",
  "Hungarian",
  "Austrian",
  "Swiss",
  "Czech",
  "Slovak",
  "Serbian",
  "Croatian",
  "Bosnian",
  "Montenegrin",
  "Bulgarian",
  "Romanian",
  "Apache",
  "Sioux",
  "Cherokee",
  "Navajo",
  "Iroquois",
  "Inuit",
  "Arawak",
  "Carib",
  "Taino",
  "Aztec",
  "Mayan",
  "Incan",
  "Mapuche",
  "Guarani",
  "Tupi",
  "Yanomami",
  "Zuni",
  "Hopi",
  "Kiowa",
  "Comanche",
  "Shoshone",
  "Japanese",
  "Ryukyu",
  "Ainu",
  "Cham",
  "Khmer",
  "Thai",
  "Vietnamese",
  "Burmese",
  "Balinese",
  "Malay",
  "Filipino",
  "Mongolian",
  "Korean",
  "Tibetan",
  "Manchu",
  "Uyghur",
  "Hmong",
  "Karen",
  "Pyu",
  "Hawaiian",
  "Fijian",
  "Tongan",
  "Samoan",
  "Maori",
  "Micronesian",
  "Hebrew",
  "Armenian",
  "Circassian",
  "Georgian",
  "Phoenician",
  "Chaldean",
  "Kurdish",
  "Turkic",
  "Kazakh",
  "Uzbek",
  "Kyrgyz",
  "Tajik",
  "Uighur",
  "Pashtun",
  "Baloch",
  "Afghan",
  "Persian",
  "Kenyan",
  "Ugandan",
  "Bhutanese",
  "Latin",
  "Moldovan",
  "Militant",
  "Spartan",
];
export const BOT_NAME_SUFFIXES = [
  "Empire",
  "Dynasty",
  "Kingdom",
  "Queendom",
  "Sultanate",
  "Confederation",
  "Union",
  "Republic",
  "Caliphate",
  "Dominion",
  "Realm",
  "State",
  "Federation",
  "Territory",
  "Commonwealth",
  "League",
  "Duchy",
  "Province",
  "Protectorate",
  "Colony",
  "Mandate",
  "Free State",
  "Canton",
  "Region",
  "Nation",
  "Assembly",
  "Hierarchy",
  "Archduchy",
  "Grand Duchy",
  "Metropolis",
  "Cluster",
  "Alliance",
  "Tribunal",
  "Council",
  "Confederacy",
  "Order",
  "Regime",
  "Dominion",
  "Syndicate",
  "Guild",
  "Corporation",
  "Patriarchy",
  "Matriarchy",
  "Legion",
  "Horde",
  "Clan",
  "Brotherhood",
  "Sisterhood",
  "Ascendancy",
  "Supremacy",
  "Province",
  "Tribe",
  "Dominion",
  "Assembly",
  "Republics",
  "Army",
  "Dictatorship",
  "Country",
  "Oligarchy",
  "Monkdom",
  "Throng",
  "Host",
  "Area",
  "District",
  "Fief",
  "Wilderness",
  "Settlement",
  "Parliament",
  "Anarchy",
  "Democracy",
  "Autocracy",
];
export const COMMUNITY_BOT_NAMES = [
  "evan the Creator",
  "iamlewis the Leader",
  "Restart the Community",
  "Mr Box the Dev",
  "InGloriousTom the Dev",
  "Sheikh the First",
  "N0ur the Flag Master",
  "Diessel the UI Master",
  "Nikola123 the Map Master",
  "Aotumuri the Linguist",
  "Pilkey the Admin",
  "Mr tryout33s",
  "Biffeur the YT",
  "Enzo the YT",
  "Molky the YT",
  "FuzeIII the YT",
  "Node the YT",
  "Lumiin the YT",
  "youngfentanyl OFM",
  "Remorse the Wiki",
  "Lonely Millennial Twitch",
  "Kaizeron OFM",
  "Zilka OFM",
  "JIZK Caster",
  "MiraCZ the FP",
  "aPuddle the Best",
  "lucas the Sound",
  "Fulayon the YT",
  "Drew durnell YT",
  "The Spiffing Brit YT",
  "Ultimus Rex YT",
  "MizuUmi the YT",
];
export const SPECIAL_BOT_NAMES = [
  "Commander",
  "General",
  "Admiral",
  "Marshal",
  "Captain",
];
export const COMMUNITY_PREFIXES = [
  "The Sparkling Bot",
  "Valentino",
  "Mr Cube",
  "Nukeman",
  "Baguette Bot",
  "Kiwi",
  "FakeNeo",
  "Toyatak",
  "Readix",
  "Danny",
  "php",
  "Redincon",
  "Sachx.",
  "Fuity Mctooty",
  "Vimacs",
  "Wraith",
  "Phantom",
  "Crescent",
  "OF Therapist",
  "Aviid",
  "brunoo",
  "Ezaru",
  "prices",
  "Santos",
  "Wonder",
  "Vincent",
  "Smith M",
  "Acer Alex",
  "Controller",
  "d3n0x",
  "devalnor",
  "FloPinguin",
  "falcon",
  "GlacialDrift",
  "Jax",
  "Killersoren",
  "MiniMeTiny",
  "Remissile",
  "Sorikairo",
  "That Otter",
  "Arya",
  "Nebula",
  "takeser",
  "Kai IL PAZZO",
  "Vanon",
  "Foorack",
  "Abod",
  "aaa4xu",
  "Goblinon",
  "dx",
  "Pod",
  "Demonessica",
  "Dovg",
  "Joel",
  "LegitimatelyCool1",
  "OxMzimzy",
  "RTHOne",
  "Egophobic",
  "djmrFunnyMan",
  "5oliloguy",
  "cfsolver",
  "nvm",
  "Supbro",
  "Mischa",
  "WALMART NINJA",
  "Magico",
  "sidious",
  "Bruny",
  "Goofer",
  "Backn",
  "EyeSeeEm",
  "TrionX",
  "Theodora",
  "platz1de",
  "Maths Empire",
  "Moha",
  "SyntaxPM",
  "theskeleton4393",
  "juliosilvaqwerty5",
  "NewHappyRabbit",
  "Moki",
  "Xaelor",
  "NiclasWK",
  "cldprv",
  "r3ms",
  "Tanepro193",
  "gx21",
  "toldinsound",
  "jacks0n",
  "floriankilian",
  "Fibig",
  "Texxter",
  "pantelispantelidis",
  "ap ms",
  "frappa10",
  "Lollosean",
  "daimyo panda2",
  "gafunuko",
  "Jinyoon",
  "Perdiccas",
  "zibi",
  "RinkyDinky",
  "Rulfam",
  "Nobody",
  "Vekser",
  "extraextra",
  "MotivatedMonkey",
  "6uzm4n",
  "theangel2",
  "Keevee",
  "Makonede",
  "grassified",
  "Zjefken",
  "Summers Nick",
  "Marvin",
  "EagleEye",
  "Shahiid",
  "INGSOC",
  "SIG",
  "Bobo",
  "seekerreturns",
  "SlyTy",
  "Leo 21",
  "FX",
  "Calrathan",
  "AzloD",
  "SunnyBoyWTF",
  "BeGj",
  "tnhnblgl",
  "BrunoJurkovic",
  "q8gazy",
  "Kipstz",
  "aqw42",
  "TylerHavanan",
  "KerodK",
  "ghisloufou",
  "dxtron",
  "Sii",
];
